### ISSUE TITLE
Problem of rendering

### ISSUE THREAD

**Issue by phicarre** [hexojs/hexo-theme-landscape#105]
Why
<a href=" <%- url_for(theme.menu[1]) %>"blabla</a>
is rendered in
<a href="/root/">blabla</a>
?
I was expected
<a href="/root/page_name.html/">blabla</a>
In fact
mysite/root/page_name.html

In other words, how to address an object in hexo ?

**Comment by tomap** [comment]
https://hexo.io/docs/helpers#url-for

url_for("path") will just render to "**your_root**/path"
so in your case, if you only obtain "/root", it might be because you don't have the right value in 
theme.menu[1]
You can try to debug:
<%= theme.menu[1] %> to check the value here

**Comment by stevenjoezhang** [comment]
Closing as answered.
