### ISSUE TITLE
Customizable Banner Image

### ISSUE THREAD

**Issue by seamlik** [hexojs/hexo-theme-landscape#106]
The current banner image seems to be hardcoded. Would be great if users can customize it via `_config.yml`.

**Comment by tomap** [comment]
The banner image is here: https://github.com/hexojs/hexo-theme-landscape/blob/master/source/css/images/banner.jpg
You can find it in your theme folder, and change the image by another

**Comment by sirkaushalkumar** [comment]
Sir/Ma'am, Yes the image is customizable. Suppose you are in your project directory, then go to this path - ```themes/landscape/source/css/images```, and add the image you wish to see as banner. Also change the name of the image to banner.jpg and delete the default one. This should fix the issue.

**Comment by seamlik** [comment]
Modifying an external module directly might not be what we want. It conflicts with the workflow of using Git submodules.
