### ISSUE TITLE
&nbsp; no decoding

### ISSUE THREAD

**Issue by izaktan** [hexojs/hexo-theme-landscape#107]
![image](https://user-images.githubusercontent.com/33599274/39344531-977c156a-4a15-11e8-9728-10556b5c2bd6.png)
I wanna leave some space between but it doesn't work. This code works under other themes.

**Comment by tomap** [comment]
You should not add space using unbreakable space, but rather using CSS.
The reason why it "does not work", is because, in this theme, the text here is htmlencoded, so the `&nbsp;` are rendered instead of being space

**Comment by tomap** [comment]
BTW, you can remove the "HTMLEncode" in your theme by removing the <%= and using <%- instead

**Comment by RammusXu** [comment]
It's doable. By changing.
```
-        <a href="<%- url_for() %>" id="logo"><%= config.title %></a>
+        <a href="<%- url_for() %>" id="logo"><%- render(config.title, 'pug'); %></a>
```

But I don't think it's good idea to use 
```
# _config.yaml
title: Ramm&nbsp;us
subtitle: A Developer
```

It's weird. Why don't we close this?
@stevenjoezhang @SukkaW
