### ISSUE TITLE
Tag Cloud - how to show more than 40 tags ?

### ISSUE THREAD

**Issue by jr0cket** [hexojs/hexo-theme-landscape#12]
I am trying to work out how to show more than 40 tags in the tag cloud.  In the tag list I see all tags (about 80), but in the tag cloud I only get 40.

Is there a configuration in the theme I can use to over-ride the default?  I assume there must be, but having spend a day trying to figure this out I would appreciate any suggestions.

Thanks
John.

**Comment by unstephenk** [comment]
Looks like no one replies here..

**Comment by Xuanwo** [comment]
No setting, maybe you need to modify the code= =

**Comment by tomap** [comment]
the tagcloud is displayed here:
https://github.com/hexojs/hexo-theme-landscape/blob/master/layout/_widget/tagcloud.ejs
and you can find the documentation of tagcloud() function here: 
https://hexo.io/docs/helpers#tagcloud

You can see that the default number of tags is 40. To have more, just pass the parameter amount.

However, the story does not ends here: If you leave the amount empty, the default value is unlimited, not 40. See the code here: 
https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/tagcloud.js#L198

I'll update documentation

Could you retest on your side, with latest version of hexo ? (3.8.0 currently)

Thank you

**Comment by YoshinoriN** [comment]
Now we are deployed new document for tag cloud.
Thanks.
