### ISSUE TITLE
How can I update fancybox to 3.x? 

### ISSUE THREAD

**Issue by mgrddsj** [hexojs/hexo-theme-landscape#122]
Fancybox 2.x is outdated, and its 3.x version is more modern and beautiful. How to update to the newest version?

**Comment by tomap** [comment]
All fancybox files have been copied to this theme
You just need to remove them 
then, copy the new ones from here:
https://github.com/fancyapps/fancybox
then check that the theme still works and submit a PR :)

**Comment by stevenjoezhang** [comment]
Fancybox updated in https://github.com/hexojs/hexo-theme-landscape/pull/144
