### ISSUE TITLE
table in article looks wired

### ISSUE THREAD

**Issue by TyrionC** [hexojs/hexo-theme-landscape#14]
In landscape,when i insert a table into an article,there is a big blank area before the table,and I hava to add margin-top style to the table to make it looks normal.By the way,the blank space is not the same size in diffrent place of the article.Why?

**Comment by tomap** [comment]
Probably a markdown plugin issue.
Could you try to update both hexo & hexo-renderer-markdown to the latest version ?

**Comment by tomap** [comment]
I'm closing this one (too old)
