### ISSUE TITLE
no category widgets

### ISSUE THREAD

**Issue by Guguant** [hexojs/hexo-theme-landscape#158]
Hi, hexojs

I have used **hexo** + **landscape theme** to build a personal blog website. And I have posted a paper with its category, but I didn't find the **category** widget on the homepage. 
Do you know what I should do to set the **category** widget? Thanks.

My personal blog website: [https://guguant.github.io/](https://guguant.github.io/)

Best.
Soleil Andyz.

**Comment by dailyrandomphoto** [comment]
@Guguant 
Did you add categories to the front-matter?
https://hexo.io/docs/front-matter#Categories-amp-Tags

Then check if the markdown file is under `/source/_posts/`. If categories have been added to a page(like /source/about/index.md), it's not works.

**Comment by Guguant** [comment]
> @Guguant
> Did you add categories to the front-matter?
> https://hexo.io/docs/front-matter#Categories-amp-Tags
> 
> Then check if the markdown file is under `/source/_posts/`. If categories have been added to a page(like /source/about/index.md), it's not works.

hi, dailyrandomphoto. According to your guide, I have not still fixed the problem 「no category widget in homepage with the hexo-landscape theme」？

**Comment by Guguant** [comment]
> > @Guguant
> > Did you add categories to the front-matter?
> > https://hexo.io/docs/front-matter#Categories-amp-Tags
> > Then check if the markdown file is under `/source/_posts/`. If categories have been added to a page(like /source/about/index.md), it's not works.
> 
> hi, dailyrandomphoto. According to your guide, I have tried it but I still didn't fixed the problem 「no category widget in homepage with the hexo-landscape theme」?

Hello, ailyrandomphoto. Do you know any ways to fix the problem?

**Comment by Guguant** [comment]
@dailyrandomphoto 
you see, right word should be **categories**, but I wrote it as **cetegories**.
