### ISSUE TITLE
tag Cloud display not refresh

### ISSUE THREAD

**Issue by csarron** [hexojs/hexo-theme-landscape#16]
when I delete some previous tag, this tag cloud widget does not refresh, namely it still display tags that is not existing!!!

**Comment by zhengkai2001** [comment]
Yes, I met the same problem.

**Comment by Xuanwo** [comment]
@csarron @threeears @zhengkai2001 Still have the problem?

**Comment by leesei** [comment]
Delete `db.json` if you are using `hexo server`.
This should not be a theme issue.
