### ISSUE TITLE
Does this project have owner

### ISSUE THREAD

**Issue by RammusXu** [hexojs/hexo-theme-landscape#175]
Hi,

How about add [code owner](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax) on this project?

It's really useful to assign tickets automatically. And if someone want to be a volunteer or someone don't want to spend time on this project anymore, just update the `CODEOWNERS` files. Let people know if this project alive.

**Comment by tomap** [comment]
You can check pulse: https://github.com/hexojs/hexo-theme-landscape/pulse/monthly and the list of commits and their date to know that. Hexo maintainer are looking over this repo

**Comment by RammusXu** [comment]
I mean,  I do know how to check project pulse. But how about add [CODEOWNER](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax) ? It will be nicer to newbie to here and make sure someone is watching pull requests.

**Comment by tomap** [comment]
Someone is watching PR :)
As you can see, this project is part of hexojs: https://github.com/hexojs
with a lot of people in it + it's the default theme for hexo :)
