### ISSUE TITLE
Support Disqus？

### ISSUE THREAD

**Issue by Restent** [hexojs/hexo-theme-landscape#178]
This theme can support Disqus & DisqusJS by myself？

**Comment by tomap** [comment]
Yes, it can

https://github.com/hexojs/hexo-theme-landscape/blob/a129596458b3d6295fd47ee86197a5aefec811c8/layout/_partial/article.ejs#L44

It's not in the readme, but it's available. Just fill the variable disqus_shortname with your disques id, and it'll works
