### ISSUE TITLE
Firefox on macOS: Code blocking area is invisible

### ISSUE THREAD

**Issue by funcrab** [hexojs/hexo-theme-landscape#179]
- Browser version: Firefox 80.0.1 (64bit)
- OS version: macOS Catalina 10.15.6 (19G2021)

Same with Firefox in safe mode
![hexo](https://user-images.githubusercontent.com/55499652/93743787-a299c080-fc2b-11ea-8b1e-84fc3724c163.png)

I'm sorry if I made any mistakes.

**Comment by stevenjoezhang** [comment]
It's a known issue of Firefox on macOS: https://github.com/highlightjs/highlight.js/issues/2694

**Comment by funcrab** [comment]
When I set "gfx.webrender.enabled" to true in about:config, referring to the following URL, it is now displayed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1520157
![image](https://user-images.githubusercontent.com/67508746/93845580-578bb600-fcdc-11ea-967a-1883f9ab496e.png)
![image](https://user-images.githubusercontent.com/67508746/93845583-5a86a680-fcdc-11ea-80ff-ebcc83b2f85c.png)

**Comment by assoft** [comment]
`Solution:` **Delete or Update Source Code Pro font from your computer.**

**Comment by funcrab** [comment]
@assoft Thanks for the information.
It doesn't seem to happen in my environment anymore, maybe it was fixed in the Firefox update.
https://bugzilla.mozilla.org/show_bug.cgi?id=1520157
In Firefox Ver83.0 the following settings are enabled.
`gfx.webrender.enabled = false` in about:config
