### ISSUE TITLE
hexo-generator-search not work in this theme

### ISSUE THREAD

**Issue by HCY-ASLEEP** [hexojs/hexo-theme-landscape#197]
I followed official docs of hexo-generator-search, but the search bar of theme-landscape still can not search locally, it will turn to google search. Can anyone tell me how to use hexo-generator-search in this theme? Or it will be great if anyone can tell me how to local search in landscape-theme without using hexo-generator-search. I am using github pages to show my blogs.

**Comment by bi-an** [comment]
I have the same question.

**Comment by uiolee** [comment]
the [readme](https://github.com/wzpan/hexo-generator-search#how-to-use-this-plugin-in-my-hexo-blog) of `hexo-generator-search` has told you how to do. use the theme which used `[hexo-generator-search](https://github.com/wzpan/hexo-generator-search)` or write script and page by yourself.

**Comment by bi-an** [comment]
您好，收到了~感谢您的来信，祝您生活愉快！
