### ISSUE TITLE
No css Applied 

### ISSUE THREAD

**Issue by kirby123-cmd** [hexojs/hexo-theme-landscape#199]
while deploying my website ,I could see CSS code applied on the website 

https://kirby123-cmd.github.io/Sometimes/

**Comment by stevenjoezhang** [comment]
Seems to be caused by incorrect configuration. Maybe you can paste your Hexo `_config.yml` file here? @kirby123-cmd

**Comment by uiolee** [comment]
Because no one provides enough information, I am going to **close** this issue. 

If the problem still exists, please **reopen** this issue and provide more information.
