### ISSUE TITLE
I have a question about languages that I would like to ask

### ISSUE THREAD

**Issue by Lete114** [hexojs/hexo-theme-landscape#202]
Why do the `en-US.yml` and `en-GB.yml` and `default.yml` files have `en.yml` in them?

Does it automatically reference the contents of the `en.yml` file? Why doesn't mine work?

My hexo version: `^6.3.0`

**Comment by stevenjoezhang** [comment]
It's called symbolic link on Linux. If you're using Windows, you may need to configure git to make it work.
