### ISSUE TITLE
Layout shifting when loading

### ISSUE THREAD

**Issue by bramcordie** [hexojs/hexo-theme-landscape#23]
The theme is slightly modified (colors and round corners) but I get the same effect on the demo page and with an unmodified theme.

I tried to capture the problem in a gif:

![animation showing the layout shifting](http://g.recordit.co/3jnyw51UHq.gif)

You can see the Adblock Plus message at the bottom, turning it off does not have any influence.

**Comment by Xuanwo** [comment]
It looks like just the font loading

**Comment by leesei** [comment]
I second.

**Comment by stevenjoezhang** [comment]
This is caused by the font loading. Different browsers may produce different behaviors, which is normal.
