### ISSUE TITLE
How to use fancybox?

### ISSUE THREAD

**Issue by flyi** [hexojs/hexo-theme-landscape#27]
Please give an example.

**Comment by unstephenk** [comment]
I would like one too

**Comment by Hunter-Github** [comment]
Click on any normal image (say, there are two in a post), and you'll be presented with a fancybox with left/right buttons.

**Comment by lzjqsdd** [comment]
Try this theme,https://github.com/A-limon/pacman,And edit themes/pacman/_config.yml,there's a fancybox option,make it true.Then the image in you post can be show in fancybox when you click the image.
Here is an example,http://www.lvzejun.cn/2015/03/31/ubuntu-software/

**Comment by unstephenk** [comment]
Cool. Thanks guys!
