### ISSUE TITLE
Search button does not send keyword query to google site: search

### ISSUE THREAD

**Issue by ootput** [hexojs/hexo-theme-landscape#28]
Whatever the search keyword I use, google only searches for site:<hexo blog url>  so essentially the results show my blog contents in no particular order.

**Comment by jamiehumphries** [comment]
This is a problem with hexo core, not the theme. See linked issue.

**Comment by uiolee** [comment]
It looks like this issue has been resolved and I will close it. 

If the problem persists, please **reopen**
