### ISSUE TITLE
Google analytics not working

### ISSUE THREAD

**Issue by thomastoye** [hexojs/hexo-theme-landscape#31]
I'm having trouble enabling Google Analytics. I have this in my `_config.yml`:

    google_analytics: "UA-48804932-1"

But I get nothing when serving. The landscape theme is the latest version (git commit `0815298a3`) and here's the output of `hexo version`:

```
hexo: 3.0.0
os: Linux 3.16-3-amd64 linux x64
http_parser: 2.3
node: 0.12.1
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

Anything I'm doing wrong here?

**Comment by unstephenk** [comment]
Same issue here

**Comment by taur-firiath** [comment]
>I have this in my _config.yml

In what file you wrote it? In *hexo _config.yml* or *themes/landscape/_config.yml*? Must be in theme config.

I set parameter without double qoutes
```
google_analytics: UA-48804932-1
```
and it works.

**Comment by thomastoye** [comment]
I ended up symlinking `themes/landscape_config.yml` to `_config.yml`. I'm
not sure if this is a solution or a workaround :)

On Mon, 26 Oct 2015 19:45 taur-firiath <notifications@github.com> wrote:

> I have this in my _config.yml
>
> In what file you wrote it? In *hexo _config.yml* or
> *themes/landscape/_config.yml*? Must be in theme config.
>
> I set parameter without double qoutes
>
> google_analytics: UA-48804932-1
>
> and it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexojs/hexo-theme-landscape/issues/31#issuecomment-151244729>
> .
>
-- 
Best regards,

Thomas Toye
Student New Media and Communication Technology
www.thomastoye.be

**Comment by leesei** [comment]
It is an issue that site config `./_config.yml` and theme config `./theme/XXX/_config.yml` are not properly defined. That being said, Landscape read GA token from theme config.
I don't think it is a good practice to symlink site config as theme config.
