### ISSUE TITLE
Translate theme

### ISSUE THREAD

**Issue by taur-firiath** [hexojs/hexo-theme-landscape#41]
Hello.
I want to translate the theme. In other themes there is languages directory with translation files. But in this theme there is no files. Why? This theme does not yet support translation? Or how do I get the default translation file with english word set to create a translation based thereon?

**Comment by Xuanwo** [comment]
This theme is built for hexo 2.4 before and not update since that time.
When I were free, I will do something to support Hexo 3, especially for i18n.

**Comment by Xuanwo** [comment]
@taur-firiath Hello, duo to https://github.com/hexojs/hexo-theme-landscape/pull/43 , now you can do your translation. please let me know whenever you have problem~

**Comment by taur-firiath** [comment]
Hello @Xuanwo.
Thank you for creating the translation files. However, these constants are not used.
In #53 I change ejs files to use constants, add Russian language and add some additional constants.

**Comment by Xuanwo** [comment]
Well, do you have a test? I'm busy in finishing homework now, and do not have time to test the changes in layout.

**Comment by taur-firiath** [comment]
Of course I tested. But only on Russian language.

**Comment by Xuanwo** [comment]
I‘m afraid of the use of `__()` func because I remember an issue report the problem of that.
And as you tested, Iwill merge it soon.

**Comment by taur-firiath** [comment]
OK.
I just use [Internationalization docs](https://hexo.io/docs/internationalization.html) and [Light theme code](http://hexo.io/hexo-theme-light)
