### ISSUE TITLE
update FontAwesome

### ISSUE THREAD

**Issue by tomByrer** [hexojs/hexo-theme-landscape#47]
The major improvement over what you have now is smaller files with [WOFF2](http://caniuse.com/#feat=woff2), but perhaps offset by all the [new icons](https://fortawesome.github.io/Font-Awesome/icons)  B)

Could use [MaxCDN](https://fortawesome.github.io/Font-Awesome/get-started), but [jsDelivr](http://www.jsdelivr.com/projects/fontawesome) has a far bigger network (with China, Africa, & India coverage).

**Comment by tomap** [comment]
Ongoing, see #126

**Comment by stevenjoezhang** [comment]
Fixed in #126
