### ISSUE TITLE
引用样式

### ISSUE THREAD

**Issue by Explorare** [hexojs/hexo-theme-landscape#51]
![OmniMarkupPreviewer](https://c.hime.io/images/j0r0.png)
![landsacpe](https://c.hime.io/images/qNnm.png)
我希望能输出和图一一样的样式，该怎么样修改呢？

**Comment by Explorare** [comment]
```
blockquote
    font-family: font-serif
    font-size: 1em
    padding: 0 15px
    text-align: left
    color: #777
    border-left: 4px solid #ddd;
    footer
      font-size: font-size
      margin: line-height 0
      font-family: font-sans
      cite
        &:before
          content: "—"
          padding: 0 0.5em
```

**Comment by real-jiakai** [comment]
blockquote
    font-family: font-serif
    font-size: 1.4em
    margin: line-height 20px
    text-align: left
    color: #777
    border-left: 2px solid #ddd
+  padding-left: 5px
    footer
      font-size: font-size
      margin: line-height 0
      font-family: font-sans
      cite
        &:before
          content: "—"
          padding: 0 0.5em

可以再加一个左边的填充间距
