### ISSUE TITLE
How to 'remove pagination of 10' and 'add counts back'

### ISSUE THREAD

**Issue by beyondai** [hexojs/hexo-theme-landscape#52]
1. How to add counts back to widgets?
   like:
   January 2016 (10)
   December 2015 (24)
   November 2015 (43)
2. How to remove 10 item pagination after click the a tag or category?
   I want to show my post simple as a list.

**Comment by lulzneko** [comment]
1. Please set `show_count: true` in the `_config.yml` file.

2. Please set `per_page: 0` of Hexo's `_config.yml` file (not this theme file).
Below is an excerpt of the configuration block:
```
# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page
```

**Comment by stevenjoezhang** [comment]
Closing as answered.
