### ISSUE TITLE
How to use the [TOC] to create a catalog?

### ISSUE THREAD

**Issue by yatesun** [hexojs/hexo-theme-landscape#56]
> I don't know how to use the [TOC] to create a catalog?

**Comment by Xuanwo** [comment]
depends on your theme.

**Comment by YateSun** [comment]
rubbish

**Comment by YateSun** [comment]
我能在这里提问，你还有必要问我是使用哪个主题？

**Comment by bennyn** [comment]
Is it possible to render a table of contents using "hexo-theme-landscape"? Hexo.js seems to offer a [Table of contents helper](https://hexo.io/docs/helpers.html#toc) but I don't know how I can render it into a post.
