### ISSUE TITLE
 "__('next')" is mistakenly put into the quote

### ISSUE THREAD

**Issue by shankerwangmiao** [hexojs/hexo-theme-landscape#57]
The problem occurs at `_partial/archive.ejs` 

```
     <%- paginator({
      prev_text: "&laquo; __('prev')",
      next_text: "__('next') &raquo;"
     }) %>
```

What a bug!

**Comment by amejiarosario** [comment]
Thanks for the fix @shankerwangmiao! I was looking into that issues too

**Comment by gkatsev** [comment]
A fix I've applied locally is to just change it to be `"&laquo; " + __('prev')` and `__('next') + " &raquo;"` and it works perfectly.

**Comment by gkatsev** [comment]
Ah, missed that PR.

**Comment by nronnei** [comment]
What is the function o f`__prev()`? I'm trying to port this theme over to the Pug template engine.

**Comment by nbkhope** [comment]
Is this issue not solved yet in 3.2.0?

**Comment by liangzelang** [comment]
@gkatsev , Great Job!!! however, the newest version doesn't use this way,  is there any difference.

**Comment by shankerwangmiao** [comment]
okay, since it has been fixed, i'll close this issue.
