### ISSUE TITLE
404 on https://hexo.io/hexo-theme-landscape/

### ISSUE THREAD

**Issue by ainthek** [hexojs/hexo-theme-landscape#60]

**Comment by ericop** [comment]
Still getting 404 on the demo page. :( Hexo is super sweet! Keep up the good work!

**Comment by Xuanwo** [comment]
Fixed now.

**Comment by ericop** [comment]
Agreed, it's up now!

**Comment by ainthek** [comment]
Thanx, only 4 days to fix :-) good job
