### ISSUE TITLE
Sometimes defaults to French language

### ISSUE THREAD

**Issue by rpcarn** [hexojs/hexo-theme-landscape#65]
After "hexo generate" sometimes Hexo Landscape is in French. Creating a "en.yml" language file may have fixed it.

**Comment by Xuanwo** [comment]
I remenber It depends on your site setting, strange.

**Comment by pritambarhate** [comment]
Don't know if this should be posted as a separate issue. This happened to me twice now. Created a new site with:

```
hexo init blog && cd blog
hexo serve
```

This results in french site. in _config.yml the language setting is empty. I would expect it to generate English by default. Setting the language explicitly to 'en' generates an English site. 

```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 1.0
node: 0.10.37
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.36
zlib: 1.2.8
modules: 11
openssl: 1.0.1l
```

I have checked this on node 6.9.1 also. Same results.

**Comment by nbkhope** [comment]
This happened to me, but it seems only for the "Recent Posts" section, which turned to "ARTICLES RÉCENTS".

**Comment by Ian729** [comment]
set hexo/_config.yml's 'language' to 'default' instead of 'en'

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://github.com/hexojs/hexo/issues/1125
I'm closing this issue. Please join the discussion there :)
