### ISSUE TITLE
Fancybox tag plugin generates malformed HTML source

### ISSUE THREAD

**Issue by seaoak** [hexojs/hexo-theme-landscape#80]
When I use fancybox tag, Hexo generates malformed HTML source:
  - "a" element is not closed (missing "`</a>`")
  - caption element is not generated despite the existence of title string

---
I found a bug in scripts/fancybox.js:21 (lack of "+" operator at the end of line)

    -    '<img src="' + (thumbnail || original) + '" alt="' + title + '">'
    +    '<img src="' + (thumbnail || original) + '" alt="' + title + '">' +

**Comment by sira313** [comment]
Thanks, i thought i was the only one who got this problem
