### ISSUE TITLE
Add post title to share button text in article.

### ISSUE THREAD

**Issue by fsubal** [hexojs/hexo-theme-landscape#83]
When clicking share button on each article, we are now seeing only the permalink URL.

![2016-12-15 2 48 50](https://cloud.githubusercontent.com/assets/5250706/21193878/2fa556cc-c271-11e6-9a7b-a4eeb7ac1168.png)

Maybe we want something like this.

```js:source/script.js
text = $this.attr('data-text'),
......
'<a href="https://twitter.com/intent/tweet?url=' + encodedUrl + '&text=' + text + '" class="article-share-twitter" target="_blank" title="Twitter"></a>',
```

**Comment by NoahDragon** [comment]
Agree. If you could submit the pull request, I would merge the change.
