### ISSUE TITLE
Google Analytics tracking code should be in <head> section

### ISSUE THREAD

**Issue by sanori** [hexojs/hexo-theme-landscape#91]
Due to https://support.google.com/webmasters/answer/35179#google_analytics_verification
Google Analytics tag should be in &lt;head&gt; section

The document of Google Analytics `analytics.js` tag said the same thing:
> The code should be added **near the top of the &lt;head&gt; tag** and before any other script or CSS tags, and the string 'UA-XXXXX-Y' should be replaced with the property ID (also called the "tracking ID") of the Google Analytics property you wish to track.

From: https://developers.google.com/analytics/devguides/collection/analyticsjs

**Comment by NoahDragon** [comment]
Thanks for the PR, merged.
