### ISSUE TITLE
Where to find the source for the rendered sample page?

### ISSUE THREAD

**Issue by kwasmich** [hexojs/hexo-theme-landscape#93]
On hexo.io there is a sample page based on the landscape theme showing all its possibilities.
https://hexo.io/hexo-theme-landscape

Unfortunately I can only find the rendered page but not the sources. As the documentation is very thin not showing every possibility, it would be nice to have some kind of sample or reference. Not everything shown on the page is clear to me so I'd really appreciate if someone can point to the sources of the sample page.

**Comment by NoahDragon** [comment]
It's in the theme unit-test repo. https://github.com/hexojs/hexo-theme-unit-test

**Comment by kwasmich** [comment]
Thank You!
