### ISSUE TITLE
Render problem with image inside a link (linked image)

### ISSUE THREAD

**Issue by noraj** [hexojs/hexo-theme-landscape#96]
Image inside a link (linked image) is not rendered properly.

Markdown:

```markdown
[![](https://ctftime.org/static/images/CTFTIME-flat-logo-true.png)](https://ctftime.org/user/16344)
```

Rendered by the web browser:

```html
<a href="https://ctftime.org/user/16344"  target="_blank" rel="external">
    <a href="https://ctftime.org/static/images/CTFTIME-flat-logo-true.png" title="" class="fancybox" rel="article0">
        <img src="https://ctftime.org/static/images/CTFTIME-flat-logo-true.png" alt="">
    </a>
</a>
```

Rendered the markdown renderer:

```html
<a href="https://ctftime.org/user/16344">
    <img src="https://ctftime.org/static/images/CTFTIME-flat-logo-true.png" alt="" title="">
</a>
```

So when a user clic on an image he go to the image location instead of the link.

The html content generated by markdown it is good. But even with fancybox set to False, there is some javascript dynamically adding a fancybox class and changing the href. 

At the end of each page there is

```html
<script src="/js/script.js"></script>
```

This script contain:

```js
[...]
// Caption
  $('.article-entry').each(function(i){
    $(this).find('img').each(function(){
      if ($(this).parent().hasClass('fancybox')) return;

      var alt = this.alt;

      if (alt) $(this).after('<span class="caption">' + alt + '</span>');

      $(this).wrap('<a href="' + this.src + '" title="' + alt + '" class="fancybox"></a>');
    });

    $(this).find('.fancybox').each(function(){
      $(this).attr('rel', 'article' + i);
    });
  });

  if ($.fancybox){
    $('.fancybox').fancybox();
  }
[...]
```

The ejs template including the script is `themes/landscape/layout/_partial/after-footer.ejs`.

Where you can see:

```ejs
[...]
<% if (theme.fancybox){ %>
  <%- css('fancybox/jquery.fancybox') %>
  <%- js('fancybox/jquery.fancybox.pack') %>
<% } %>

<%- js('js/script') %>
```

So `<%- js('js/script') %>` is included even if theme.fancybox is false and that script is generating the problem.

The fancybox part of the code need be out of `script.js` and put in another script inside the condition statement `<% if (theme.fancybox){ %>`.

**Comment by NoahDragon** [comment]
Thank you for digging into the code. I think this could be an enhancement.

**Comment by tomap** [comment]
Fixed!
