### ISSUE TITLE
请问站主:使用你的这个主题出现本地搜索框与下面的最新文章重合的问题怎么解决？

### ISSUE THREAD

**Issue by KangShanR** [hexojs/hexo-theme-landscape#97]
看过了你的主页，应该是下面的最新文章的框往上浮，与左边主体框对齐了，就出现了与本来应该在它上面的本地搜索框重合，搜索框还是在上层。

**Comment by NoahDragon** [comment]
能否贴下截屏，或者网站链接？

**Comment by KangShanR** [comment]
[image: Inline image 1]是这个样子的

**Comment by KangShanR** [comment]
网站链接：http://kangshan.oschina.io/
背景图片我换了下。

**Comment by KangShanR** [comment]
![image](https://user-images.githubusercontent.com/26142142/30190454-cb57b556-946c-11e7-9a88-2361c775c976.png)这是图片

**Comment by NoahDragon** [comment]
在css样式中将#search-form的position改为relative即可修复此问题。
```
#search-form {
    position: relative;
    bottom: -52px;
    right: 0;
    padding: 20px 0;
    color: #333;
    width: 25%;
}
```

**Comment by tomap** [comment]
Can we close this one? @NoahDragon @KangShanR ?
